name: Run tweeter bot

on:
  schedule:
    - cron: "05 14 * * *" #10am
    - cron: "05 17 * * *" #3pm
    - cron: "05 23 * * *" #7pm
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run script
        env:
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          KEY: ${{ secrets.KEY }}
          consumer_key: ${{secrets.consumer_key}}
          consumer_secret: ${{secrets.consumer_secret}}
          access_token: ${{secrets.access_token}}
          access_token_secret: ${{secrets.access_token_secret}}
        run: python main.py
